image: alpine:edge

services:
  - docker:dind

stages:
  - build-docker

variables:
  REPOSITORY: $CI_REGISTRY/javier/movistar-u7d

before_script:
  - apk update && apk add docker docker-cli-buildx
  - docker run --privileged --rm tonistiigi/binfmt --install all
  - docker buildx create --name mybuilder
  - docker buildx use mybuilder
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

build-docker:
  stage: build-docker
  script:
    - docker buildx build --platform linux/amd64,linux/arm64,linux/arm/v7 --push --tag $REPOSITORY:latest --tag $REPOSITORY:`date +%Y%m%d%H%M%` .
  only:
    - master
