version: '2.4'

services:
  movistar_u7d:
    # build: .
    image: registry.marcet.info/javier/movistar-u7d
    container_name: movistar_u7d
    cap_add:
      - NET_ADMIN
      - NET_BROADCAST
      - SYS_ADMIN
      - SYS_NICE
    restart: on-failure
    network_mode: host
    dns:
      - 172.26.23.3
      - 127.0.0.1
    volumes:
      - /etc/localtime:/etc/localtime
    # - ./:/app
    # - ${HOME}:/home
    # - ${RECORDINGS}:${RECORDINGS}
    #environment:
    # - DEBUG=${DEBUG}
    # - EPG_THREADS=${EPG_THREADS}
    # - IPTV_BW=${IPTV_BW}
    # - LAN_IP=${LAN_IP}
    # - MP4_OUTPUT=${MP4_OUTPUT}
    # - RECORDING_THREADS=${RECORDING_THREADS}
    # - RECORDINGS=${RECORDINGS}
    # - SANIC_PORT=${SANIC_PORT}
    # - U7D_UID=${U7D_UID}
    # - VERBOSE_LOGS=${VERBOSE_LOGS}
    # devices:
    #   - /dev/dri:/dev/dri
    # cpu_shares: 8192
    # cpus: 4
    # mem_limit: 3gb
    # memswap_limit: 3gb
    # healthcheck:
    #   test: ping -c 1 -W 1 www-60.svc.imagenio.telefonica.net | grep -q '172.26.22.23' && nc -vz ${SANIC_HOST} 8888
    #   interval: 30s
    #   timeout: 5s
    #   retries: 3

# vim: et ci pi sts=2 sw=2 ts=2
